## NumPy is homogeneous collection data

In [16]:
ls1 = [1,2,3,"Sumit", "Shukla"]

In [17]:
np.array(ls1)

array(['1', '2', '3', 'Sumit', 'Shukla'], dtype='<U11')

## Memory Consumption

In [1]:
# Let's create a list

ls = [1,2,3,4]
print(ls)

[1, 2, 3, 4]


In [7]:
import sys

print("The memory cosumed by one element of the list: {} Bytes".format(sys.getsizeof(4)))

The memory cosumed by one element of the list: 28 Bytes


**1Byte = 8 Bits**

In [8]:
print("Total memory consumption by list: {} Bytes".format(len(ls)*sys.getsizeof(1)))

Total memory consumption by list: 112 Bytes


In [9]:
## Check consumption of NumPy Array

import numpy as np

In [10]:
np_arr = np.array(ls)

In [11]:
# NumPy array
np_arr

array([1, 2, 3, 4])

In [13]:
print("Memory consumed by NumPy to save one element of a NumPy array: {} Bytes".format(np_arr.itemsize))

Memory consumed by NumPy to save one element of a NumPy array: 4 Bytes


In [14]:
# Size will return the number of elements we have in a numpy array
np_arr.size

4

In [15]:
print("Total memory consumption by NumPy array: {} Bytes".format(np_arr.size*np_arr.itemsize))

Total memory consumption by NumPy array: 16 Bytes


## Pointer allocation in case of NumPy and Lists

is: Identity check

==: Equality check

In [18]:
ls

[1, 2, 3, 4]

In [19]:
np_arr

array([1, 2, 3, 4])

In [29]:
# Let's extract one element of a list
ls[0] is ls[0]

True

In [31]:
np_arr[0] is np_arr[0]

False

In [32]:
ls[0] == ls[0]

True

In [33]:
np_arr[0] ==np_arr[0]

True

In [35]:
np_arr+1

array([2, 3, 4, 5])

## Speed

In [37]:
import time as ts

ls1 = list(range(10000000))
np_arr1 = np.array(ls1)

t1 = ts.time()
ls2 = [i+1 for i in ls1]
t2 = ts.time()

print("The time take by list process: {} ms".format((t2-t1)*1000))

t3 = ts.time()
np_arr2 = np_arr1+1
t4 = ts.time()

print("The time taken by NumPy array process: {} ms".format((t4-t3)*1000))

The time take by list process: 3410.2611541748047 ms
The time taken by NumPy array process: 47.03164100646973 ms


## Working with NumPy

In [39]:
ls = [1,2,3,4,5]
np_arr = np.array(ls)

In [40]:
type(np_arr)

numpy.ndarray

In [41]:
# Rank-1 array
# 1-D array
np_arr

array([1, 2, 3, 4, 5])

In [48]:
np_arr.shape

(5,)

In [42]:
ls1 = [[1,2,3], [4,5,6], [7,8,9]]
np_arr1 = np.array(ls1)

In [43]:
# 2-D array
# 3 rows and 3 Columns
np_arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np_arr1.shape

(3, 3)

In [44]:
# 3D array

import cv2

img = cv2.imread(r'C:\Users\SUMITH\Python Notebooks\Python Notebooks\YouTube Content\mother_teresa.jpg')

In [46]:
img.shape

(600, 640, 3)

## Inspecting elements of NumPy array

In [49]:
# Number of Dimensions: ndim

print(np_arr.ndim)
print(np_arr1.ndim)
print(img.ndim)

1
2
3


In [50]:
# Shape of a NumPy array: shape

print(np_arr.shape)
print(np_arr1.shape)
print(img.shape)

(5,)
(3, 3)
(600, 640, 3)


In [54]:
# Total number of elements in a NumPy array: size

print(np_arr.size)
print(np_arr1.size)
print(img.size)

5
9
1152000


In [53]:
# Check datype of NumPy elements: dtype

print(np_arr.dtype)
print(np_arr1.dtype)
print(img.dtype)

# 1Byte = 8Bits

int32
int32
uint8


In [56]:
# Memory consumption by each element is a NumPy array: itemsize

print(np_arr.itemsize, "Bytes")
print(np_arr1.itemsize, "Bytes")
print(img.itemsize, "Byte")

4 Bytes
4 Bytes
1 Byte


## Functions with NumPy

### Reshape

In [58]:
# reshape: A lower dimensional NumPy array to higher dimension

np_arr = np.array([1,2,3,4,5,6,7,8,9])
np_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np_arr.ndim

1

In [62]:
np_arr_2d = np_arr.reshape(3,3)

In [63]:
np_arr_2d.ndim

2

In [68]:
np.array([1,2,3]).reshape(3,3)

ValueError: cannot reshape array of size 3 into shape (3,3)

### Arange

In [64]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
# arange is a replica of range function which we have in lists
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Random

In [76]:
# random.random will help us to create a numpy array with random numbers in creatin shape
np.random.random((3,3))

array([[0.2739315 , 0.14930209, 0.18761301],
       [0.69646959, 0.52408996, 0.34208797],
       [0.77026312, 0.10562377, 0.27023054]])

In [134]:
# random.randint: it will return you a random number between the specified range

np.random.randint(0,100)

56

In [89]:
# random.randn: it will return you n random number

np.random.randn(5)

array([-0.81607356,  0.22709777,  0.8072496 , -0.80795638,  0.59416044])

### Central Tendency Function

In [135]:
a = np.random.random((3,3))

In [136]:
a

array([[0.60011303, 0.75788629, 0.32589155],
       [0.73820592, 0.02849229, 0.75245064],
       [0.80159019, 0.23259844, 0.22207974]])

In [137]:
# overall mean
np.mean(a)

0.49547867641444665

In [138]:
# Column wise mean
np.mean(a, axis=1)

array([0.56129696, 0.50638295, 0.41875612])

In [139]:
# row wise mean
np.mean(a, axis = 0)

array([0.71330305, 0.33965901, 0.43347398])

## Stacking

In [147]:
np_1 = np.arange(12).reshape((3,4))
np_2 = np.arange(20).reshape((5,4))

print(np_1)

print("-------------------")
print(np_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [149]:
#verticle stack
np.vstack((np_1, np_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [152]:
#horizontal stack
np_1 = np.arange(20,40).reshape((5,4))
np_2 = np.arange(20).reshape((5,4))

np.hstack((np_1, np_2))

array([[20, 21, 22, 23,  0,  1,  2,  3],
       [24, 25, 26, 27,  4,  5,  6,  7],
       [28, 29, 30, 31,  8,  9, 10, 11],
       [32, 33, 34, 35, 12, 13, 14, 15],
       [36, 37, 38, 39, 16, 17, 18, 19]])

## Matrix Multiplication

In [153]:
np_1 = np.arange(1,10).reshape(3,3)
np_2  = np.arange(1,13).reshape(3,4)

print(np_1)
print("------------")
print(np_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [154]:
np.dot(np_1, np_2)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

## Linalg

In [155]:


# inv: inverse of a matix
np.linalg.inv(np_1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [156]:
# det: deteriment of a matrix

np.linalg.det(np_1)

6.66133814775094e-16

In [157]:
# eig: Eigen values and eigen vectors

np.linalg.eig(np_1)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [159]:
np_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
# Transformation of a matrix
np_1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])